name: Build, Test, & Publish '@jalexw/mould' NPM Package

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-test-and-publish:
    name: "Build, test, & publish NPM package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Install dependencies with Bun
        run: bun install
      - name: Build package with Bun
        run: bun run build
      - name: Run package unit tests
        run: bun run test
      - name: Publish package
        run: bun publish --registry=https://npm.pkg.github.com
        env:
          GITHUB_PACKAGE_REGISTRY_USER: ${{ github.actor }}
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
